name: Compile Agda and Deploy HTML
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:

# Install Agda
    - name: Install Agda
      run: sudo apt-get install -y agda-bin      

# Download and compile main library
    - name: Checkout main
      uses: actions/checkout@v2

    - name: Install Python      
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.9'

    - name: Type Checking
      run: python check-proofs.py