name: Proof Checking and Deploy HTML
on: [push]

jobs:
  proof-checking:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout main
      uses: actions/checkout@v3

    - name: Install Agda
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: agda
        version: 2.6.2.2-1.1build1  

    - name: Generate Agda Modules for Proof Checking
      shell: pwsh
      run: .\generate-modules.ps1

    - name: Proof Checking
      run: agda --html --html-dir=docs index.agda    

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.2.2
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      with:
        BRANCH: gh-pages
        FOLDER: docs   
