name: Compile Agda and Deploy HTML
on:
  push:
    branches:
      - main

env:
  AGDA_VERSION: 2.6.2.2-1.1build1
  PYTHON_VERSION: 3.10.7

jobs:
  proof-checking:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout main
      uses: actions/checkout@v2

    - name: Update APT
      run: sudo apt-get update    

    - name: Install Agda
      run: |
        sudo apt-get install agda
        sudo agda --version

    - name: Install Python      
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Generate Agda File for Proof Checking
      run: python generate-complete-agda-file.py

    - name: Proof Checking
      run: agda --html --html-dir=docs index.agda

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.2.2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs   
