name: Compile Agda and Deploy HTML
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        cubical-ref: ["a60b0c6576fac0ba6e181cab75f9f9de2d167f87"]
        agda-ref: ["v2.6.2"]
        ghc-ver: ["9.0.1"]
        cabal-ver: ["3.4.0.0"]

    steps:

# Install Agda


# Download and compile main library
    - name: Checkout main
      uses: actions/checkout@v2

    - name: install python
      if: steps.cache-main.outputs.cache-hit != 'true'      
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.9'

    - name: type checking
      if: steps.cache-main.outputs.cache-hit != 'true'      
      run: python check-proofs.py
