name: Compile Agda and Deploy HTML
on: [push]

env:
  AGDA_VERSION: 2.6.2.2-1.1build1  

jobs:
  proof-checking:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout main
      uses: actions/checkout@v2

    - name: Update APT
      run: sudo apt-get update    

    - name: Install Agda
      run: |
        sudo apt-get install agda
        sudo agda --version

    - name: Install Powershell      
      run: |
        sudo apt-get install -y powershell

    - name: Generate Agda Modules for Proof Checking
      run: .\generate-modules.ps1

    - name: Proof Checking
      run: agda --html --html-dir=docs index.agda    

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.2.2
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      with:
        BRANCH: gh-pages
        FOLDER: docs   
