name: Compile Agda and Deploy HTML
on:
  push:
    branches:
      - main

jobs:
  build:
    container: davidstahl97/agda
    steps:
    
    - name: Checkout main
      uses: actions/checkout@v2

    - name: Install Python      
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.9'

    - name: Generate Agda File for Proof Checking
      run: python generate-complete-agda-file.py

    - name: Proof Checking
      run: agda everything.agda