name: Proof Checking and Deploy HTML
on: [push]

env:
  AGDA_VERSION: 2.6.0.1-1build4

jobs:
  proof-checking:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout main
      uses: actions/checkout@v3

    - name: Update APT
      run: sudo apt-get update 
